import { Roboto_Mono, Satisfy } from "next/font/google";
import LoginModal from "./components/modals/LoginModal";
import RegisterModal from "./components/modals/RegisterModal";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";
import { NextAuthProvider } from "./provider";
import ToasterProvider from "./providers/ToasterProvider";

const roboto = Roboto_Mono({ weight: "400", subsets: ["latin"] });
const satisfy = Satisfy({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-satisfy",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${roboto.className} ${satisfy.variable}`}>
      <body>
        <NextAuthProvider>
          <ToasterProvider />
          <Navbar />
          <LoginModal />
          <RegisterModal />
          <main className="flex h-full items-center justify-center pt-20">
            {children}
          </main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
