import { Poppins, Roboto_Mono, Satisfy } from "next/font/google";
import Navbar from "./components/navbar/Navbar";
import "./globals.css";

const poppins = Poppins({ weight: "400", subsets: ["latin"] });
const roboto = Roboto_Mono({ weight: "400", subsets: ["latin"] });
const satisfy = Satisfy({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-satisfy",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${roboto.className} ${satisfy.variable}`}>
      <body>
        <Navbar />
        <main className="flex h-full items-center justify-center pt-20">
          {children}
        </main>
      </body>
    </html>
  );
}
